name: Reddit - InkWisps

on:
  schedule:
    - cron: '30 19 * * *'  # 01:00 AM IST
    - cron: '0 21 * * *'
    - cron: '30 22 * * *'
    - cron: '0 0 * * *'
    - cron: '30 1 * * *'
    - cron: '0 3 * * *'
    - cron: '30 4 * * *'
    - cron: '0 6 * * *'
    - cron: '30 7 * * *'
    - cron: '0 9 * * *'
    - cron: '30 10 * * *'
    - cron: '0 12 * * *'
    - cron: '30 13 * * *'
    - cron: '0 15 * * *'
    - cron: '30 16 * * *'
  workflow_dispatch:

jobs:
  reddit_post:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
      DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
      REDDIT_REFRESH_TOKEN: ${{ secrets.REDDIT_REFRESH_TOKEN }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system ffmpeg (fast)
        run: |
          sudo add-apt-repository ppa:jonathonf/ffmpeg-4 -y
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install praw dropbox requests python-telegram-bot moviepy opencv-python ffmpeg-python pytz

      - name: Run Reddit Bot
        run: python "reddit.py"
